package com.piclib.web.dao;

import com.piclib.web.entity.License;
import com.piclib.web.entity.LicenseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface LicenseMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_license
     *
     * @mbg.generated
     */
    long countByExample(LicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_license
     *
     * @mbg.generated
     */
    int deleteByExample(LicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_license
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_license
     *
     * @mbg.generated
     */
    int insert(License record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_license
     *
     * @mbg.generated
     */
    int insertSelective(License record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_license
     *
     * @mbg.generated
     */
    List<License> selectByExample(LicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_license
     *
     * @mbg.generated
     */
    License selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_license
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") License record, @Param("example") LicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_license
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") License record, @Param("example") LicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_license
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(License record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_license
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(License record);
}