package com.piclib.web.dao;

import com.piclib.web.entity.MaterialCategory;
import com.piclib.web.entity.MaterialCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MaterialCategoryMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_category
     *
     * @mbg.generated
     */
    long countByExample(MaterialCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_category
     *
     * @mbg.generated
     */
    int deleteByExample(MaterialCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_category
     *
     * @mbg.generated
     */
    int insert(MaterialCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_category
     *
     * @mbg.generated
     */
    int insertSelective(MaterialCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_category
     *
     * @mbg.generated
     */
    List<MaterialCategory> selectByExample(MaterialCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_category
     *
     * @mbg.generated
     */
    MaterialCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MaterialCategory record, @Param("example") MaterialCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MaterialCategory record, @Param("example") MaterialCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MaterialCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterialCategory record);
}